[package]
name = "markov-chainz"
version = "0.1.0"
edition = "2021"


[dependencies]
bincode = { version = "1.3", default-features = false }
rand = { version = "0.8", default-features = true }
serde = { version = "1.0", features = ["derive"] }
